name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build_cmake:
    name: CMake Build & Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DELFIO_BUILD_EXAMPLES=YES -DELFIO_BUILD_TESTS=YES
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
    - name: Test
      run: |
        cd build
        ctest -C ${{ matrix.build_type }}
        cd ..
