[book]
authors = ["LostbBlizzard"]
title = "UCodeDocumentation"
description = "The book about UCodeLang"

[output.html]
language = "en"
multilingual = false
src = "src"
git-repository-url = "https://github.com/LostbBlizzard/UCodeLang"
edit-url-template = "https://github.com/LostbBlizzard/UCodeLang/tree/master/doc/src/{path}"
