name: Deployment

on: workflow_dispatch
   inputs:
      VersionNumber:
        description: 'The New Version Number Ex: "1.2.3"'
        required: true
        type: string
        default: "0.0.0"
      IsPreRelease:
        description: 'Is Prelease'
        required: true
        type: boolean
        default: true
      
      LanguageChangelog:
       description: 'The Main Change Log'
        required: false
        type: string
        default: 'added: fixed: removed:'

      ImplementerChangelog:
       description: 'The Change Log for implmenters(People who use this as a Scripting Lang Lib)'
        required: false
        type: string
        default: 'added: fixed: removed:'

      LSPChangelog:
        description: 'The Change Log for Editor Extenions'
        required: false
        type: string
        default: 'added: fixed: removed:'


jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run:  echo "Do Build Here"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: Release ${{ inputs.VersionNumber }}
          body: |
            LanguageChangelog Changelog:
            ${{ inputs.MainChangelog }}

            Implementers Changelog:
            ${{ inputs.MainChangelog }}

            LSP Changelog:
            ${{ inputs.LSPChangelog }}

          draft: false
          prerelease: false
