name: CI

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - './**.c'
      - './**.h'
      - './**.hpp'
      - './**.cpp'
  workflow_dispatch:
    branches:
      - feature

jobs:

  msbuild-windows-64bit-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake Install Tools
      run: premake installtools

    - name: Run Premake
      run: premake vs2022

    - name: Build 64 bit
      run: premake build

    - name: RunTests for 64 bit
      run: premake test

  msbuild-windows-32bit-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake Install Tools
      run: premake installtools

    - name: Run Premake
      run: premake vs2022

    - name: Build 32 bit
      run: premake build_32bit

    - name: RunTests for 32 bit
      run: premake test_32bit

  gmake-linux-build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake Install
      run: premake installtools

    - name: Run Premake
      run: premake gmake2

    - name: Build 64 bit
      run: premake build

    - name: RunTests for 64 bit
      run: premake test

  clang-macos-build:
   runs-on: macos-latest

   steps:
    - uses: actions/checkout@v3

    - name: Add Premake to PATH
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake Install Tools
      run: premake installtools

    - name: Run Premake
      run: premake gmake2

    - name: Build 
      run: premake build

    - name: RunTests
      run: premake test

  gmake-wasm-build:
   if: 'false'
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Add Emsdk to PATH
      uses: mymindstorm/setup-emsdk@v13

    - name: Run Premake
      run: premake gmake2
    
    - name: Build Wasm
      run: premake web_build
 
  clang-android-build:
   if: 'false'
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake 
      run: premake gmake2

  clang-ios-build:
   if: 'false'
   runs-on: "macos-latest"
   steps:
    - uses: actions/checkout@v3

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake 
      run: premake gmake2

