name: CI

on:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  msbuild-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Premake
      run: ./VS_2019.bat

    - name: Build 32 bit
      run: ./BuildTools/BuildWin32Debug.bat

    - name: Build 64 bit
      run: ./BuildTools/BuildWin64Debug.bat
    
    - name: RunTests for 32 bit
      run: ./BuildTools/RunTestsWin32Debug.bat

    - name: RunTests for 64 bit
      run: ./BuildTools/RunTestsWin64Debug.bat