name: CI

on:
  pull_request:
  push:
    branches:
      - master
      
jobs:

  msbuild-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Premake
      run: ./VS_2019.bat


    - name: Restore cached objs
      id: cache-objs-restore
      uses: actions/cache/restore@v3
      with:
        path: ./Output
        key: ${{ runner.os }}-1

    - name: Build 64 bit
      run: |
           cd ./BuildTools
           ./BuildWin64Debug.bat

    - name: Build 32 bit
      run: |
           cd ./BuildTools
           ./BuildWin32Debug.bat

    - name: Save cached Objs
      id: cache-Objs-save
      uses: actions/cache/save@v3
      with:
        path: ./Output
        key: ${{ steps.cache-objs-restore.outputs.cache-primary-key }}

    - name: RunTests for 64 bit
      run: |
           cd ./BuildTools
           ./RunTestsWin64Debug.bat

  gmake-linux-build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Make a scripts executable
      run: |
       chmod +x ./GNU_Make.sh
       chmod +x ./BuildTools/BuildLinux32Debug.sh
       chmod +x ./BuildTools/BuildLinux64Debug.sh
       chmod +x ./BuildTools/RunTestsLinux32Debug.sh
       chmod +x ./BuildTools/RunTestsLinux64Debug.sh

    - name: Run Premake
      run: ./GNU_Make.sh
    
    - name: Restore cached objs
      id: cache-objs-restore
      uses: actions/cache/restore@v3
      with:
        path: ./Output
        key: ${{ runner.os }}-cl-1inux

    - name: Build 64 bit
      run: make UCodelangCL config=debug_linux64

    - name: Save cached Objs
      id: cache-Objs-save
      uses: actions/cache/save@v3
      with:
        path: ./Output
        key: ${{ steps.cache-objs-restore.outputs.cache-primary-key }}

    - name: RunTests for 64 bit
      run: ./BuildTools/RunTestsLinux64Debug.sh
