name: CI

on:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  msbuild-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Premake
      run: ./VS_2019.bat

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ./UCodeLang.sln
    
